### ISSUE TITLE
Rewrite?

### ISSUE THREAD

**Issue by GoogleGenius** [magnifydev/magnify#21]
A lot of the JS and CSS is quite horrendous if you look at it closely. I myself have had to work with how the CSS was initially written and it's a limiting factor in my opinion. I don't think anything warrants a rewrite yet until people actually use this hopefully in the upcoming school year, definitely v2024.0.0 if it gets to that. We've moved the current infrastructure for JS over to TS so it hopefully scales better. At least a CSS rewrite would be nice for now, redoing the class names, removing redundant properties, etc. I think the JSX needs to be split into more components too.

**Comment by Ascent817** [comment]
Yeah I totally agree. I think we should at least fix some of the css. I'm not very good with css though, so if someone else can rewrite that would be good. Also, do you think it's a good idea to break up the course into two components, one for editing and one for viewing?
React doesn't like the hacky code I used to get the text out of the courses
We really should be using a form and then capturing that data

**Comment by Ascent817** [comment]
I can refactor the course editing and viewing if we decide that's something we want to do.

**Comment by GoogleGenius** [comment]
Also Magnify behaves like a React 17 app still because we're using the ReactDOM.render still

**Comment by Ascent817** [comment]
Is there a simple fix for that?

**Comment by GoogleGenius** [comment]
> Is there a simple fix for that?

I'm not sure, the way React creates the root element or whatever is different in react 18. You might want to look at how it's setup by create-react-app in my website code https:///github.com/GoogleGenius/erich

**Comment by GoogleGenius** [comment]
I'm going to close this issue and open several smaller ones instead, so we have a better workable step-by-step goal.
