### ISSUE TITLE
Add contact form

### ISSUE THREAD

**Issue by Ascent817** [magnifydev/magnify#23]

**Comment by GoogleGenius** [comment]
Closed by #22

**Comment by Ascent817** [comment]
This still isn't there in the latest release. I'm reopening.

**Comment by GoogleGenius** [comment]
What happened?

**Comment by Ascent817** [comment]
This issue can't be close because there isn't a contact modal in the website

**Comment by Ascent817** [comment]
Oh I'm stupid. I couldn't see the contact button. I would make it more visible, maybe as a side panel icon instead of a floating button.

**Comment by Ascent817** [comment]
Rip. Time to reopen.
![image](https://user-images.githubusercontent.com/86618650/181830918-56c4d25d-dae3-41fa-816b-989bfc21bcbe.png)
It doesn't work.

**Comment by GoogleGenius** [comment]
@Ascent817 is this the live instance or what?

**Comment by GoogleGenius** [comment]
It works fine for me

**Comment by Ascent817** [comment]
This is on the live instance, windows chrome laptop, in the guest window

**Comment by GoogleGenius** [comment]
![image](https://user-images.githubusercontent.com/81032623/181831641-b210b3c1-b234-412c-92f6-1ad5bfcfe82c.png)

**Comment by GoogleGenius** [comment]
Weird bug?

**Comment by GoogleGenius** [comment]
I can see the promise failing in your screenshot but it doesn't happen for me
