### ISSUE TITLE
Search icon is a bit off?

### ISSUE THREAD

**Issue by Ascent817** [magnifydev/magnify#24]
![image](https://user-images.githubusercontent.com/86618650/181626711-eff68a1f-3ddd-4cf8-a2bf-35e41cb7a874.png)
Notice how the search icon is a bit lower than it should be. Let me know what you think.
![image](https://user-images.githubusercontent.com/86618650/181627150-800721a5-2f3e-4913-a54a-dc65f975b781.png)
This is more of where I think the search icon should be

**Comment by GoogleGenius** [comment]
you're right, it has to do with a fix I had for the old version where the icon kept shifting away for some reason on reload. I'll adjust the padding.
