### ISSUE TITLE
Implement lazy loading of course elements and data

### ISSUE THREAD

**Issue by GoogleGenius** [magnifydev/magnify#52]
The website is horrendous on slower devices lol

**Comment by Ascent817** [comment]
I think lazy loading is nice, but it isn't possible with the way the code was written(badly). We'd need to do a significant refactor of the way that the courses are loaded for it to be possible.

**Comment by GoogleGenius** [comment]
I guess this will be backlogged. I think the priority now is on refactoring out the components.

**Comment by GoogleGenius** [comment]
Right now the components are loaded by looping through the data essentially and creating a component element for each part of the course data we receive. I also was thinking about an implementation detail that could have been overlooked, which is that when trying to jump down to a particular element (if we were to add that feature, which I think I will sometime soon), that may be an issue because the element isn't loaded yet, therefore not having the respective id tag which we could update the browser URL maybe.
