### ISSUE TITLE
Add indeterminate spinner to contact form submission

### ISSUE THREAD

**Issue by Ascent817** [magnifydev/magnify#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It's difficult to know whether the form sent successfully because there is no feedback when you click the button. Only if you wait 5 - 10 seconds does the form close and a popup appear

### Describe the Solution

Change the submit button to a spinner on submit to show that the form is currently sending

**Comment by GoogleGenius** [comment]
I implemented something like this before (just modifying text) but it didn't work properly.
